export type Slot = "top" | "pants" | "shoes" | "hat" | "accessory";
export const jobs = [
  {
    id: "papers",
    name: "Zeitungen austragen",
    icon: "📰",
    category: "Nachbarschaft",
    pay: 38,
    xp: 14,
    seconds: 12,
    level: 1,
    prompt: "Die Abkürzung führt durch einen Garten. Was machst du?",
    choices: [
      "Auf dem Gehweg bleiben",
      "Durch die Blumen laufen",
      "Zeitungen einfach werfen",
    ],
    answer: 0,
  },
  {
    id: "shelves",
    name: "Regale einräumen",
    icon: "🛒",
    category: "Einzelhandel",
    pay: 48,
    xp: 18,
    seconds: 15,
    level: 1,
    prompt: "Welches Produkt kommt nach vorne?",
    choices: [
      "Das mit dem längsten Datum",
      "Das mit dem kürzesten Datum",
      "Das teuerste",
    ],
    answer: 1,
  },
  {
    id: "lawn",
    name: "Rasen mähen",
    icon: "🌱",
    category: "Nachbarschaft",
    pay: 55,
    xp: 20,
    seconds: 18,
    level: 1,
    prompt: "Der Rasen ist nass. Dein Plan?",
    choices: [
      "Volle Geschwindigkeit",
      "Sicherheit prüfen und langsam mähen",
      "Mit der Schere beginnen",
    ],
    answer: 1,
  },
  {
    id: "delivery",
    name: "Lieferfahrer",
    icon: "🚲",
    category: "Gastronomie",
    pay: 65,
    xp: 24,
    seconds: 20,
    level: 2,
    prompt: "Zwei Lieferungen: Eis und Pizza. Wer zuerst?",
    choices: ["Pizza", "Eis", "Erst selbst essen"],
    answer: 1,
  },
  {
    id: "flea",
    name: "Flohmarkt-Profi",
    icon: "📦",
    category: "Vertrieb",
    pay: 72,
    xp: 25,
    seconds: 22,
    level: 2,
    prompt: "Ein Käufer bietet 12 €, du möchtest 15 €.",
    choices: [
      "Freundlich 14 € anbieten",
      "Den Käufer beleidigen",
      "Auf 100 € erhöhen",
    ],
    answer: 0,
  },
  {
    id: "tutor",
    name: "Nachhilfe geben",
    icon: "📚",
    category: "Bildung",
    pay: 90,
    xp: 30,
    seconds: 25,
    level: 3,
    prompt: "Was sind 15 % von 200?",
    choices: ["15", "30", "45"],
    answer: 1,
  },
  {
    id: "support",
    name: "IT-Support",
    icon: "💻",
    category: "IT",
    pay: 110,
    xp: 35,
    seconds: 28,
    level: 4,
    prompt: "Der Computer geht nicht an. Erster Check?",
    choices: ["Neue Grafikkarte", "Stromversorgung", "Betriebssystem löschen"],
    answer: 1,
  },
  {
    id: "craft",
    name: "Werkstatt-Aushilfe",
    icon: "🔧",
    category: "Handwerk",
    pay: 125,
    xp: 40,
    seconds: 30,
    level: 5,
    prompt: "Vor der Reparatur einer Maschine …",
    choices: ["Strom trennen", "YouTube starten", "Mit dem Hammer testen"],
    answer: 0,
  },
  {
    id: "sales",
    name: "Junior Sales",
    icon: "☎️",
    category: "Vertrieb",
    pay: 150,
    xp: 45,
    seconds: 35,
    level: 6,
    prompt: "Dein Kunde ist unsicher. Du …",
    choices: [
      "hörst zu und klärst den Bedarf",
      "versprichst alles",
      "legst auf",
    ],
    answer: 0,
  },
  {
    id: "analyst",
    name: "Finance Analyst",
    icon: "📊",
    category: "Finanzen",
    pay: 200,
    xp: 60,
    seconds: 40,
    level: 8,
    prompt: "Umsatz 800 €, Kosten 650 €. Gewinn?",
    choices: ["1.450 €", "150 €", "650 €"],
    answer: 1,
  },
];
export const industries = [
  {
    id: "kiosk",
    name: "Kiosk",
    icon: "🏪",
    cost: 500,
    revenue: 18,
    costs: 6,
    description: "Kleine Marge. Große Stammkundschaft.",
    accent: "#eab56a",
  },
  {
    id: "clothing",
    name: "Clothing Brand",
    icon: "✦",
    cost: 1200,
    revenue: 42,
    costs: 19,
    description: "Mach aus einem Hoodie einen Hype.",
    accent: "#b6a0e9",
  },
  {
    id: "food",
    name: "Streetfood",
    icon: "🍜",
    cost: 1800,
    revenue: 64,
    costs: 34,
    description: "Guter Geschmack zahlt sich aus.",
    accent: "#ef9e83",
  },
  {
    id: "software",
    name: "Software Studio",
    icon: "⌘",
    cost: 4000,
    revenue: 112,
    costs: 53,
    description: "Hohe Fixkosten. Digitales Wachstum.",
    accent: "#8cbcc5",
  },
];
export const upgrades = [
  ["sign", "Neues Ladenschild", "marketing", 120, 0.08],
  ["social", "Social Media", "marketing", 240, 0.12],
  ["quality", "Bessere Materialien", "quality", 350, 0.15],
  ["tools", "Neue Ausstattung", "production", 450, 0.18],
  ["checkout", "Schneller Checkout", "production", 600, 0.2],
  ["website", "Eigene Website", "marketing", 750, 0.24],
  ["training", "Team-Training", "quality", 900, 0.28],
  ["supply", "Lieferantenvertrag", "production", 1200, 0.32],
  ["automation", "Automatisierung", "production", 1800, 0.4],
  ["location", "Zweiter Standort", "expansion", 3000, 0.65],
].map(([id, name, type, price, boost]) => ({
  id: String(id),
  name: String(name),
  type: String(type),
  price: Number(price),
  boost: Number(boost),
}));
const roles = [
  "Verkäufer",
  "Barista",
  "Designer",
  "Entwickler",
  "Marketing Manager",
  "Buchhalter",
  "Manager",
  "Produktion",
  "Logistik",
  "Kundenservice",
  "Analyst",
  "Produktmanager",
  "Fotograf",
  "Filialleitung",
  "Recruiter",
];
export const employees = roles.map((role, i) => ({
  id: `employee-${i}`,
  name: [
    "Mila",
    "Ben",
    "Yuki",
    "Noah",
    "Lina",
    "Emil",
    "Ada",
    "Omar",
    "Zoe",
    "Leo",
    "Nia",
    "Finn",
    "Ivy",
    "Toni",
    "Alex",
  ][i],
  role,
  skill: 35 + i * 4,
  salary: 3 + Math.floor(i / 3) * 2,
  hireCost: 90 + i * 40,
  boost: 0.18 + i * 0.025,
}));
const names = [
  "Essential Tee",
  "Studio Hoodie",
  "Wide Leg",
  "Daily Runner",
  "Club Cap",
  "Silver Link",
  "Night Jacket",
  "Cargo 01",
  "Court Low",
  "Oval Shades",
  "Heavy Tee",
  "Archive Hoodie",
  "Tailored Pants",
  "Cloud Sneaker",
  "Script Cap",
  "Chrome Watch",
  "Varsity Jacket",
  "Raw Denim",
  "Track Runner",
  "Gold Link",
  "Signature Tee",
  "Velvet Hoodie",
  "Pleated Pants",
  "Orbit Sneaker",
  "Crown Cap",
  "Obsidian Watch",
  "Atelier Jacket",
  "Silk Trousers",
  "Phantom High",
  "Halo Chain",
];
const slots: Slot[] = [
  "top",
  "top",
  "pants",
  "shoes",
  "hat",
  "accessory",
  "top",
  "pants",
  "shoes",
  "accessory",
];
const colors = [
  "#d6d2c5",
  "#647860",
  "#37403c",
  "#e3e0d5",
  "#9e7b53",
  "#c4c6c2",
  "#343a33",
  "#8a806b",
  "#eee7d7",
  "#343434",
];
export const items = names.map((name, i) => ({
  id: `item-${i}`,
  name,
  brand: ["NØRD", "OFF HOURS", "MAISON VOID"][Math.floor(i / 10)],
  slot: slots[i % 10],
  color: colors[i % 10],
  price:
    [45, 110, 75, 150, 55, 180, 220, 130, 190, 95][i % 10] *
    (1 + Math.floor(i / 10) * 4),
  aura: 8 + i * 6,
  rarity: i < 10 ? "Common" : i < 20 ? "Rare" : "Legendary",
}));
export const achievements = [
  ["first-band", "FIRST BAND", "Verdiene 1.000 €", 1000],
  ["ceo", "CEO", "Gründe deine erste Firma", 1],
  ["fresh", "FRESH", "Erreiche 1.000 Aura", 1000],
  ["millionaire", "MILLIONAIRE", "Erreiche 1 Mio. € Vermögen", 1000000],
  ["mogul", "MOGUL", "Besitze 5 Firmen", 5],
  ["billionaire", "BILLIONAIRE", "Erreiche 1 Mrd. € Vermögen", 1000000000],
  ...[
    "Erste Schicht",
    "Schichtheld",
    "Workaholic",
    "Erster Fit",
    "Stylist",
    "Sammler",
    "Teamplayer",
    "Arbeitgeber",
    "Upgrade",
    "Optimierer",
    "Profitabel",
    "Aufsteiger",
    "Veteran",
    "Trendsetter",
  ].map((n, i) => [
    `badge-${i}`,
    n,
    [
      "1 Job abschließen",
      "10 Jobs abschließen",
      "50 Jobs abschließen",
      "1 Item kaufen",
      "5 Items kaufen",
      "15 Items kaufen",
      "1 Mitarbeiter einstellen",
      "5 Mitarbeiter einstellen",
      "1 Upgrade kaufen",
      "5 Upgrades kaufen",
      "100 € passiv verdienen",
      "Level 5 erreichen",
      "Level 10 erreichen",
      "100 Aura erreichen",
    ][i],
    i + 1,
  ]),
].map(([id, name, description, target]) => ({
  id: String(id),
  name: String(name),
  description: String(description),
  target: Number(target),
}));
export const money = (cents: number) =>
  new Intl.NumberFormat("de-DE", {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: 0,
  }).format(cents / 100);
