import assert from 'node:assert/strict';
const origin=process.env.TEST_ORIGIN||'http://localhost:3000';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const request=async(path,{cookie,body,method}={})=>{const r=await fetch(origin+path,{method:method||(body?'POST':'GET'),headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],data:await r.json()};};
const suffix=Date.now().toString(36);
const landing=await fetch(origin);assert.equal(landing.status,200);assert.match(await landing.text(),/Let’s build your empire/);
const a=await request('/api/auth',{body:{mode:'register',username:'Smoke_'+suffix,password:'test-password-123'}});assert.equal(a.status,200);const cookie=a.cookie;assert.ok(cookie);
let state=await request('/api/game',{cookie});assert.equal(state.data.player.cash,10000);const id=state.data.player.id;
assert.equal((await request('/api/game',{body:{type:'buy',id:'item-0'}})).status,401);
assert.equal((await request('/api/game',{cookie,body:{type:'found',industry:'kiosk',name:'Not Yet'}})).status,400);
state=await request('/api/game',{cookie,body:{type:'startJob',id:'papers'}});assert.equal(state.status,200);const nonce=state.data.player.activeJob.nonce;
await delay(600);assert.equal((await request('/api/game',{cookie,body:{type:'finishJob',nonce,choice:0}})).status,400);
await delay(12000);state=await request('/api/game',{cookie,body:{type:'finishJob',nonce,choice:0,cash:999999999}});assert.equal(state.status,200);assert.equal(state.data.player.cash,14750);
await delay(600);assert.equal((await request('/api/game',{cookie,body:{type:'finishJob',nonce,choice:0}})).status,400);
state=await request('/api/game',{cookie,body:{type:'buy',id:'item-0'}});assert.equal(state.status,200);assert.equal(state.data.player.cash,10250);
await delay(600);state=await request('/api/game',{cookie,body:{type:'equip',id:'item-0'}});assert.equal(state.status,200);assert.equal(state.data.aura,8);assert.equal(state.data.player.fit.top,'item-0');
const b=await request('/api/auth',{body:{mode:'register',username:'Other_'+suffix,password:'test-password-123'}});assert.equal(b.status,200);assert.ok((await request('/api/game',{cookie:b.cookie})).data.leaderboard.some(p=>p.id===id));
const sharedPage=await fetch(origin+'/player/'+id);assert.equal(sharedPage.status,200);assert.match(await sharedPage.text(),/Milestones/);
const crossSite=await fetch(origin+'/api/game',{method:'POST',headers:{Cookie:cookie,Origin:'https://attacker.example','Content-Type':'application/json'},body:JSON.stringify({type:'buy',id:'item-1'})});assert.equal(crossSite.status,403);
const profile=await request('/api/profile?id='+id);assert.equal(profile.status,200);assert.equal(profile.data.aura,8);assert.equal(profile.data.cash,undefined);
assert.equal((await request('/api/auth',{cookie,method:'DELETE'})).status,200);assert.equal((await request('/api/game',{cookie})).data.player,null);
const signin=await request('/api/auth',{body:{mode:'login',username:'Smoke_'+suffix,password:'test-password-123'}});assert.equal(signin.status,200);assert.equal((await request('/api/game',{cookie:signin.cookie})).data.player.cash,10250);
console.log('HTTP smoke passed: landing, accounts, shared leaderboard, timed reward, replay rejection, clothing, avatar, public profile, logout and persistence.');
